enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "apk"
excluded-patches = "'Hide timestamp'"
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
build-mode = "apk"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[GooglePhotos]
build-mode = "apk"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
arch = "both"
included-patches = "'Custom header for YouTube Music' 'Spoof client'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[Music-Extended-Beta]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
patches-version = "dev"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
arch = "both"
included-patches = "'Custom header for YouTube Music' 'Spoof client'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
included-patches = "'Custom header for YouTube' 'MaterialYou' 'Hide Shorts dimming'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Disable splash animation'"

[YouTube-Extended-Beta]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
patches-version = "dev"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
included-patches = "'Custom header for YouTube' 'MaterialYou'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Disable splash animation'"

[Reddit-Extended]
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"


[TikTok]
enabled = false
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
